Feature/SWEHY-15
Vendic/hyva-checkout-create-account pull request #6
Opened 2023-10-02 08:08 UTC by Zaahed

## Resolves the following issues:
- #1
- #2
- #3 

## Changelog

### Added
- [SWEHY-15](https://app.clickup.com/t/6651913/SWEHY-15): New setting to disable/enable create account checkbox.
- [SWEHY-15](https://app.clickup.com/t/6651913/SWEHY-15): New setting to toggle password mail sender.
- [SWEHY-15](https://app.clickup.com/t/6651913/SWEHY-15): New setting to configure email template for password mail sender.

2023-10-05 13:51 UTC, Tjitse-E requested changes
@Zaahed  after testing i'm getting the following error:

```
TypeError: Vendic\HyvaCheckoutCreateAccount\Model\Config::getNewPasswordTemplate(): Return value must be of type string, null returned 
```

Could you set a default value for the new password template?

2023-10-06 07:21 UTC, Zaahed commented
> @Zaahed after testing i'm getting the following error:
> 
> ```
> TypeError: Vendic\HyvaCheckoutCreateAccount\Model\Config::getNewPasswordTemplate(): Return value must be of type string, null returned 
> ```
> 
> Could you set a default value for the new password template?

Done

2023-10-06 07:59 UTC, Tjitse-E approved these changes

2023-10-06 08:47 UTC, Tjitse-E commented
@glevhen  could you do the final testing?

2023-10-09 08:52 UTC, glevhen approved these changes

2023-10-09 08:52 UTC, merged